server:
  port: 8090

spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 3397184387@qq.com
    password: lvdzsrpkhbupciha
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  # 文件上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      resolve-lazily: true

# 日志路径
logging:
  file:
    path: auth-service/logs/auth-service.log