spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/follows/**,/vp/**
            - Path=!/vp/letter-upload-images

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/register/**,/login/**

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/messages/**

        - id: letters-service
          uri: lb://letter-service
          predicates:
            - Path=/letters/**

    sentinel:
      transport:
        dashboard: localhost:9527
      enabled: true


server:
  port: 8081

logging:
  file:
    path: gateway/logs/gateway.log