spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/register/**,/login/**

    sentinel:
      transport:
        dashboard: localhost:9527
      enabled: true


server:
  port: 8081

logging:
  file:
    path: gateway/logs/gateway.log