spring:
  application:
    name: gateway
  data:
    redis:
      host: localhost
      password: 667667
      port: 6379
  cloud:
    gateway:
      enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path=/users/**

        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/register/**

    sentinel:
      transport:
        dashboard: localhost:9527
      enabled: true

    cloud:
      nacos:
        discovery:
          server-addr: localhost:8848


server:
  port: 8081

############## Sa-Token ?? (??: https://sa-token.cc) ##############
sa-token:
  # token ??????? cookie ???
  token-name: satoken
  # token ????????? ??30??-1 ??????
  timeout: 2592000
  # token ??????????????? token ???????????????????-1 ??????????
  active-timeout: -1
  # ?????????????? ?? true ???????, ? false ??????????
  is-concurrent: false
  # ????????????????? token ?? true ????????? token, ? false ????????? token?
  is-share: false
  # token ?????????uuid?simple-uuid?random-32?random-64?random-128?tik?
  token-style: uuid
  # ????????
  is-log: true

logging:
  file:
    path: gateway/logs/gateway.log