spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamer-plus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      password: 667667
      port: 6379

  mail:
    host: smtp.qq.com
    port: 465
    username: 2185866695@qq.com
    password: tpzvvxdtnflcdibc
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      resolve-lazily: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  profiles:
    active: prod

logging:
  file:
    path: auth-service/logs/auth-service.log


############## Sa-Token ?? (??: https://sa-token.cc) ##############
sa-token:
  # token ??????? cookie ???
  token-name: satoken
  # token ????????? ??30??-1 ??????
  timeout: 2592000
  # token ??????????????? token ???????????????????-1 ??????????
  active-timeout: -1
  # ?????????????? ?? true ???????, ? false ??????????
  is-concurrent: false
  # ????????????????? token ?? true ????????? token, ? false ????????? token?
  is-share: false
  # token ?????????uuid?simple-uuid?random-32?random-64?random-128?tik?
  token-style: uuid
  # ????????
  is-log: true


# MyBatis-Plus ??
mybatis-plus:
  #  mapper.xml ???resources/mapper ???xml?
  mapper-locations: classpath:mapper/*.xml
  #  ???????entity????
  type-aliases-package: com.dreamer.auth.entity
  configuration:
    #  ????????
    map-underscore-to-camel-case: true
    #  ?????SQL?????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #  ??????
      id-type: auto
      #  ????????????????
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: null

server:
  port: 8090