spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:

#        排除的路径不让外部访问
        - id: internal-api-block
          uri: lb://auth-service
          predicates:
            - Path=/vp/letter-upload-images
          filters:
            - SetStatus=403

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/follows/**,/vp/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/register/**,/login/**

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/messages/**

        - id: letters-service
          uri: lb://letter-service
          predicates:
            - Path=/letters/**

    sentinel:
      transport:
        dashboard: localhost:9527
      enabled: true


server:
  port: 8081

logging:
  file:
    path: gateway/logs/gateway.log